library/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LogoutView



app_name = 'library'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('info-register/', InformationView.as_view(), name='info-register'),


    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='library:login'), name='logout'),

    path('books/', BookView.as_view(), name='book-list'),
    path('book/create/', BookCreate.as_view(), name='book-create'),
    path('book/<slug:pk>/', BookDetail.as_view(), name= 'book'),
    path('book/<slug:pk>/update/', BookUpdate.as_view(), name='book-update'),
    path('book/<slug:pk>/delete/', BookDelete.as_view(), name='book-delete'),



    path('students/', StudentView.as_view(), name='student-list'),
    path('student/create/', StudentCreate.as_view(), name='student-create'),
    path('student/<slug:pk>/', StudentDetail.as_view(), name='student-detail'),
    path('student/<slug:pk>/update/', StudentUpdate.as_view(), name='student-update'),
    path('student/<slug:pk>/delete/', StudentDelete.as_view(), name='student-delete'),



    path('borrowers/', BorrowerView.as_view(), name='borrower-list'),
    path('borrower/create/', BorrowerCreate.as_view(), name='borrower-create'),
    path('borrower/<slug:pk>/', BorrowerDetail.as_view(), name= 'borrower'),
    path('borrower/<slug:pk>/update/', BorrowerUpdate.as_view(), name='borrower-update'),
    path('borrower/<slug:pk>/delete/', BorrowerDelete.as_view(), name='borrower-delete'),



]

library/models.py
from django.db import models
from django.contrib.auth.models import User
# Used to generate urls by reversing the URL patterns
from django.urls import reverse
from django.db.models.signals import post_save
from django.contrib.auth.models import PermissionsMixin
from django.utils.timezone import now
import uuid
import random
# relation containg all genre of books

from datetime import date, timedelta, datetime
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


class MyAccountManager(BaseUserManager):
    def create_user(self, email, name, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            name=name,



        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
            name=name,

        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Account(AbstractBaseUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, unique=True,
                          default=uuid.uuid4, editable=False)
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    name = models.CharField(max_length=60, unique=False)
    username = models.CharField(max_length=30, unique=True)
    enrollment_no = models.IntegerField(
        unique=True, default=random.randint(10000, 99999))
    date_joined = models.DateTimeField(
        verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    pic = models.ImageField(blank=True, upload_to='students')
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'username']

    objects = MyAccountManager()

    def __str__(self):
        return f'{self.name}'

        # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

        # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True


class Genre(models.Model):
    name = models.CharField(
        max_length=200, help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)")

    def __str__(self):
        return self.name
# __str__ method is used to override default string returnd by an object


# relation containing language of books
class Language(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def __str__(self):
        return self.name

# book relation that has 2 foreign key genre language
# book relation can contain multiple genre so we have used manytomanyfield


class Book(models.Model):
    id = models.UUIDField(primary_key=True, unique=True,
                          default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            help_text='13 Character https://www.isbn-international.org/content/what-isbn')
    genre = models.ManyToManyField(
        Genre, help_text="Select a genre for this book")
    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)
    total_copies = models.IntegerField()
    pic = models.ImageField(blank=True, null=True, upload_to='books')
    available_copies = models.IntegerField(name='available_copies')

    # __str__ method is used to override default string returnd by an object
    def __str__(self):
        return self.title


# relation containing info about Borrowed books
# it has  foriegn key book and student for refrencing book and student
# roll_no is used for identifing students
# if a book is returned than corresponding tuple is deleted from database
class Borrower(models.Model):
    id = models.UUIDField(primary_key=True, unique=True,
                          default=uuid.uuid4, editable=False)
    student = models.ForeignKey('Account', on_delete=models.CASCADE)
    book = models.ForeignKey('Book', on_delete=models.CASCADE)
    issue_date = models.DateField(
        null=True, blank=True, help_text='YYYY-MM-DD', default=date.today)
    return_date = models.DateField(
        null=True, blank=True, help_text='YYYY-MM-DD')

    def __str__(self):
        return self.student.name.title()+" borrowed "+self.book.title.title()

    def fine(self):
        today = date.today()
        fine = 0
        if self.return_date <= today:
            fine += 5 * (today - self.return_date).days
        return fine


class InformationForm(models.Model):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    name = models.CharField(max_length=60, unique=False)
    username = models.CharField(max_length=30, unique=True)
    student = models.BooleanField(default=False)

    def __str__(self):
        return self.email

library/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from .models import Account


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'name', 'username','enrollment_no', 'password1', 'password2','pic' )


class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")


class AccountUpdateForm(forms.ModelForm):

	class Meta:
		model = Account
		fields = ('email','name' ,'username', 'pic' )

	def clean_email(self):
		email = self.cleaned_data['email']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(email=email)
		except Account.DoesNotExist:
			return email
		raise forms.ValidationError('Email "%s" is already in use.' % account)

	def clean_username(self):
		username = self.cleaned_data['username']
		try:
			account = Account.objects.exclude(pk=self.instance.pk).get(username=username)
		except Account.DoesNotExist:
			return username
		raise forms.ValidationError('Username "%s" is already in use.' % username)

library/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView, FormView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy
from .forms import *
from django.http import request
from datetime import datetime, timedelta
from django.contrib import messages


class UserAccessMixin(PermissionRequiredMixin):
    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('library:home')
        return super(UserAccessMixin, self).dispatch(request, *args, **kwargs)




class UserLoginView(LoginView):
    template_name='library/login.html'
    fields='__all__'
    redirect_authenticated_user=True

    def get_success_url(self):
        return reverse_lazy('library:home')

class InformationView(CreateView):
    template_name='library/information_form.html'
    model=InformationForm
    context_object_name="account_register"
    fields=['email', 'name', 'username', 'student']
    success_url=reverse_lazy('library:login')

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(InformationView, self).form_valid(form)


class HomeView(LoginRequiredMixin, TemplateView):
    template_name='library/main.html'
    

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['accounts']=Account.objects.all()
        context['books'] = Book.objects.all()
        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['books']=context['books'].filter(
                title__startswith=search_input)

        context['search_input']=search_input
        return context


class BookView(LoginRequiredMixin, ListView):
    model=Book
    context_object_name='books'

    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        context['books']=context['books']

        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['books']=context['books'].filter(
                title__startswith=search_input)

        context['search_input']=search_input

        return context



class BookCreate(LoginRequiredMixin, UserAccessMixin, CreateView):
    model=Book
    permission_required= 'books.add_books'
    fields='__all__'
    success_url=reverse_lazy('library:book-list')


    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(BookCreate, self).form_valid(form)



class BookDetail(LoginRequiredMixin, DetailView):
    model=Book
    context_object_name='book'
    template_name='library/book.html'


    


class BookUpdate(LoginRequiredMixin,UserAccessMixin,  UpdateView):
    model=Book
    permission_required = 'books.change_books'
    fields='__all__'
    success_url=reverse_lazy('library:book-list')


class BookDelete(LoginRequiredMixin,UserAccessMixin,  DeleteView):
    model=Book
    permission_required = 'books.delete_book'
    context_object_name='book'
    fields='__all__'
    success_url=reverse_lazy('library:book-list')



class StudentView(LoginRequiredMixin, UserAccessMixin, ListView):
    model=Account
    context_object_name='students'
    permission_required = 'students.view_students'
    template_name='library/student_list.html'

    def get_context_data(self,  *args,**kwargs):
        context=super().get_context_data(**kwargs)
        context['students']=context['students'].exclude(is_admin=True)
        search_input=self.request.GET.get('search-area') or ''
        if search_input:
            context['students']=context['students'].filter(name__startswith=search_input)

        context['search_input']=search_input

        return context

class StudentDetail(LoginRequiredMixin, DetailView):
    model=Account
    context_object_name='student'
    template_name='library/student.html'




class StudentCreate(UserAccessMixin, CreateView):
    template_name = 'library/register.html'
    form_class = RegistrationForm
    permission_required = 'users.add_users'
    success_url = reverse_lazy('library:student-list')

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super(StudentCreate, self).form_valid(form)


class StudentUpdate(LoginRequiredMixin, UpdateView):
    form_class = AccountUpdateForm
    template_name = 'library/student_update.html'
    model = Account
    success_url=reverse_lazy('library:student-list')
    

    def form_valid(self, form):
        user = form.save()
        return super(StudentUpdate, self).form_valid(form)

class StudentDelete(LoginRequiredMixin,UserAccessMixin,  DeleteView):
    model=Account
    template_name = 'library/student_confirm_delete.html'
    permission_required = 'users.delete_users'
    context_object_name='student'
    fields='__all__'
    success_url=reverse_lazy('library:student-list')


class BorrowerView(LoginRequiredMixin, ListView):
    model=Borrower
    context_object_name='borrowers'
    template_name = 'library/borrower_list.html'


    def get_context_data(self, **kwargs):
        context=super().get_context_data(**kwargs)
        if self.request.user.is_admin or self.request.user.is_superuser:
            context['borrowers']=context['borrowers']
        else:
            context['borrowers']=context['borrowers'].filter(student = self.request.user.id)


        return context



class BorrowerCreate(LoginRequiredMixin, UserAccessMixin, CreateView):
    model=Borrower
    permission_required= 'borrowers.add_borrowers'
    fields='__all__'
    success_url=reverse_lazy('library:borrower-list')

   #remember to get the object using slug or 404 
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        book = Book.objects.get(id=instance.book.id)
        student = Account.objects.get(id=instance.student.id)
        #get the book id from the form and check if the book is still available, then subtract.
        if book.available_copies > 0:
           book.available_copies -= 1
           book.save()
           instance.save()
           messages.success(self.request, "successful")
        messages.error(self.request, "Book not in stock")
        return redirect(reverse_lazy('library:borrower-list'))



class BorrowerDetail(LoginRequiredMixin,  DetailView):
    model=Borrower()
    context_object_name='borrower'
    template_name='library/borrower.html'
    


class BorrowerUpdate(LoginRequiredMixin,UserAccessMixin,  UpdateView):
    model=Borrower
    permission_required = 'borrowers.change_borrowers'
    fields='__all__'
    success_url=reverse_lazy('library:borrower-list')


class BorrowerDelete(LoginRequiredMixin,UserAccessMixin,  DeleteView):
    model=Borrower
    permission_required = 'borrowers.delete_borrowers'
    context_object_name='borrower'
    fields='__all__'
    success_url=reverse_lazy('library:borrower-list')


    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        book = Book.objects.get(id=self.object.book.id)
        book.available_copies +=1
        book.save()
        self.object.delete()
        return redirect('library:borrower-list')

library/templates/library/base.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Library Management System</title>
  </head>
  <style>


    .card-img-top {
    width: 100%;
    height: 15vw;
    object-fit: cover;
    }
    .card{
      margin: 1em auto;
    }
    .about__img {
    margin-top: 1em;
    justify-self: center;
    }
    .profile{
      margin: auto;
      text-align: center;
      font-family: 'Gill Sans', 'Gill Sans MT', 'Calibri', 'Trebuchet MS', sans-serif;
     
    }
    .about__img img {
    width: 200px;
    border-radius: .5rem;
    }
    label {
            padding-top: 10px !important;
            display: block;
        }
    th,td{
      text-align: center;
      margin: auto;
    }
    .flex-container{
      overflow: auto;
    }


  </style>
  <body class="container">
    
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'library:home' %}">Digital Library</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'library:home' %}">Home</a>
              </li>


              
              
                {% if request.user.is_superuser or request.user.is_admin %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Students
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'library:student-list' %}">Students List</a></li>
                  <li><a class="dropdown-item" href="{% url 'library:student-create'%}">Add Student</a></li>
                 
                </ul>
              </li>
              {% endif %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Books
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'library:book-list' %}">Books List</a></li>
                  {% if request.user.is_superuser or request.user.is_admin %}
                  <li><a class="dropdown-item" href="{% url 'library:book-create' %}">Add New Book</a></li>
                  <li><a class="dropdown-item" href="{% url 'library:borrower-create' %}">Issue a Book</a></li>
                 {% endif %}
                 <li><a class="dropdown-item" href="{% url 'library:borrower-list' %}">Books Issued</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Profile
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'library:student-detail' request.user.id%}">View Profile</a></li>
                  <li><a class="dropdown-item" href="{%url 'library:logout'%}">Logout</a></li>
                 
                </ul>
              </li>
              {% endif %}
            </ul>
            <form  method="GET" class="d-flex">
              <input class="form-control me-2" type="text" placeholder="Search" name="search-area" aria-label="Search" value="{{search_input}}">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
<div class="contaner" style="overflow: auto;">
{% block content %}  {% endblock content %}</div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    
  </body>
</html>

library/templates/library/book.html
{% extends 'library/base.html' %}
{% block content %}
<div class="profile">
{% if book.pic %}
<div class="about__img img">
    <img src="{{book.pic.url}}" alt="">
</div>
{% else %}
<div class="about__img img">
    <img src="/static/avatar/open-book-clipart-03.png" alt="">
</div>
{% endif %}
{% if request.user.is_admin or request.user.is_superuser %}
<a  href="{% url 'library:book-update' book.id%}">Edit</a>
{% endif %}
<span><h1>{{book.title|title}}</h1></span>
<p style="width: 50%; margin: auto;">{{book.summary}}</p>
<p><h4 style="margin: auto;">Genre:</h4> {{book.genre.all|join:', '}}</p>
<p> <h4 style="margin: auto;">ISBN:</h4>  {{book.isbn}}</p>



</div>
{% endblock content %}

library/templates/library/book_form.html
{% extends 'library/base.html' %}
{% block content %}




<div class="card-body" >
    <a href="{% url 'library:book-list' %}">&#8592;Back</a>
    <form method="POST" enctype="multipart/form-data"action="">
    {%csrf_token%}
    <label >{{form.title.label}} </label>
    {{form.title}} 
    
    <label >{{form.author.label}} </label>
    {{form.author}} 
    <label >{{form.summary.label}} </label>
    {{form.summary}}
    
    <label >{{form.isbn.label}} </label>
    {{form.isbn}} 
    
    <label >{{form.genre.label}}</label>
    {{form.genre}} 
    
    <label >{{form.language.label}} </label> 
    {{form.language}}  
    
    <label >{{form.total_copies.label}}</label> 
    {{form.total_copies}}
    <label >{{form.available_copies.label}}</label> 
    {{form.available_copies}}
    <label >{{form.pic.label}}</label> 
    {{form.pic}}

    <label> <input class="button" type="submit" value="Submit"></label>
    
    </form>
</div>



{% endblock content %}

library/templates/library/borrower.html
<h1>{{borrower}}</h1>

library/templates/library/borrower_confirm_delete.html
{% extends 'library/base.html' %}
{% block content %}


<div >
    <a href="{% url 'library:borrower-list' %}">&#8592;Back</a>
</div>

<div >
    <form method = "POSt">
        {%csrf_token%}
        <p>Are you sure you want to delete the book issued by'{{borrower|title}}'?</p>
        <input class="button" type="submit" value="Submit">
        </form>
</div>



{% endblock content %}

library/templates/library/borrower_form.html
{% extends 'library/base.html' %}
{% block content %}




<div  class="card-body">
    <a href="{% url 'library:borrower-list' %}">&#8592;Back</a>
    <form method="POST" action="">
    {%csrf_token%}
    <label >{{form.student.label}} </label>
    {{form.student}} 
    
    <label >{{form.book.label}} </label>
    {{form.book}} 
    <label >{{form.issue_date.label}} </label>
    {{form.issue_date}}
    
    <label >{{form.return_date.label}} </label>
    {{form.return_date}} 
    

    <label> <input class="button"  type="submit" value="Submit"></label>



    </form>
</div>


{% endblock content %}

library/templates/library/borrower_list.html
{% extends "library/base.html" %} {% block content %}

<table class="table" style="margin: auto;">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Student Name</th>
      <th scope="col">Book</th>
      <th scope="col">Return Date</th>
      <th scope="col">Fine</th>
      {% if request.user.is_admin or request.user.is_superuser %}
      <th scope="col">Action</th>{% endif %}
    </tr>
  </thead>
  {% if borrowers %}
  <tbody>
    {% for borrower in borrowers %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{borrower.student.name}}</td>
      <td>{{borrower.book.title}}</td>
      <td>{{borrower.return_date}}</td>
      <td>{{borrower.fine}}</td>
      <td>{% if request.user.is_admin or request.user.is_superuser %}
        <a href="{% url 'library:borrower-update' borrower.id%}">Update</a>  <a href="{% url 'library:borrower-delete' borrower.id%}">Delete</a>
        {% endif %}</td>
    </tr>

    {% endfor %}
  </tbody>
  {% else %}
  <tbody><tr><td colspan="6"> No Books Issued.</td></tr></tbody>
  {% endif %}
</table>

{% endblock %}

library/templates/library/information_form.html
{% extends 'library/base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="profile">
<div >
    
    <a href="{% url 'library:login' %}">&#8592; Back</a>
</div>

<div >
    <h3>Fill in the form and the admins will register you and send the credentials in your email within 24 hours.</h3>
    <form method="POST" action="">
    {%csrf_token%}
    {{form|crispy}}
    <input class="button" type="submit" value="Submit">
    
    </form>
</div>

</div>

{% endblock content %}

library/templates/library/main.html
{% extends 'library/base.html' %} {% block content %}


<div class="row" style="margin: auto;">

{% for book in books %}

<div class="card" style="width: 18rem">
  <span style="text-align: center;"></span>
  {% if book.pic %}
  <img src="{{book.pic.url}}" class="card-img-top" alt="" />
  {% else %}
  <img src="/static/avatar/open-book-clipart-03.png" class="card-img-top" alt="">
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{book.title}}</h5>
    <p class="card-text">{{book.summary}}</p>
    <a href="{% url 'library:book' book.id %}" class="btn btn-primary"
      >View Details</a
    >
  </div>
</div>


{% endfor %}


</div>

{% endblock content %}

library/templates/library/register.html
{% extends 'library/base.html' %}
{% block content %}



<div class="card-body">
    <a href="{% url 'library:student-list' %}">&#8592;Back</a>
    <form method="POST" enctype="multipart/form-data" action="">
        {%csrf_token%}
        
        <label >{{form.email.label}} <span>(Add a valid email)</span></label>
        {{form.email}} 
        
        <label >{{form.name.label}} </label>
        {{form.name}} 
        
        <label >{{form.username.label}} </label>
        {{form.username}} 
        
        <label >{{form.enrollment_no.label}}</label>
        {{form.enrollment_no}} 
        
        <label >{{form.password1.label}} <span>(8 characters & alphanumeric)</span></label> 
        {{form.password1}}  
        
        <label >{{form.password2.label}}</label> 
        {{form.password2}}

        <label >{{form.pic.label}}</label> 
        {{form.pic}}

        <label> <input class="button" type="submit" value="Submit"></label>
        
        
        </form>
       
</div>




{% endblock content %}

library/templates/library/student.html
{% extends 'library/base.html' %}
{% block content %}
<div class="profile">
{% if student.pic %}
<div class="about__img img">
    <img src="{{student.pic.url}}" alt="">
</div>
{% else %}
<div class="about__img img">
    <img src="/static/avatar/images.png" alt="">
</div>
{% endif %}
<p><h1>{{student.name|title}}</h1></p>
<p>Enrollment No: {{student.enrollment_no}}</p>
<p>Date Joined: {{student.date_joined}}</p>
<a  href="{% url 'library:student-update' student.id%}">Edit Profile</a>
</div>
{% endblock content %}

library/templates/library/student_confirm_delete.html
{% extends 'library/base.html' %}
{% block content %}


<div >
    <a href="{% url 'library:student-list' %}">&#8592;Back</a>
</div>

<div >
    <form method = "POST">
        {%csrf_token%}
        <p>Are you sure you want to remove '{{student|title}}'?</p>
        <input class="button" type="submit" value="Submit">
        </form>
</div>



{% endblock content %}

library/templates/library/student_list.html
{% extends "library/base.html" %} {% block content %}
<table class="table"  style="margin: auto;">
  <thead>
    <tr>
      <th scope="col">SN</th>
      <th scope="col">Student Name</th>
      <th scope="col">Email</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  {% if students %}
  <tbody>
    {% for student in students %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{student.name}}</td>
      <td>{{student.email}}</td>
      <td><a href="{% url 'library:student-update' student.id%}">Update</a>  <a href="{% url 'library:student-delete' student.id%}">Delete</a>  <a href="{% url 'library:student-detail' student.id%}">Profile</a> </td>
    </tr>
    {% endfor %}
  </tbody>
  {% else %}
  <tbody><tr><td colspan="6"> No Students.</td></tr></tbody>
  {% endif %}
</table>
{% endblock %}

library/templates/library/student_update.html
{% extends 'library/base.html' %}
{% block content %}


<div class="card-body">

    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        
        {{form.as_p}}

            <input style="margin-top: 10px;" class="button" type="submit" value="Update">
        
        
        </form>

</div>




{% endblock content %}
        
<label >{{form.email.label}} <span>(Add a valid email)</span></label>
{{form.email}} 

<label >{{form.name.label}} </label>
{{form.name}} 

<label >{{form.username.label}} </label>
{{form.username}} 

<label >{{form.pic.label}} </label>
{{form.pic}} 